### ISSUE TITLE
export private key bash history dangers

### ISSUE THREAD

**Issue by polus-arcticus** [bacalhau-project/lilypad#2]
https://protos.com/brazilian-crypto-streamer-loses-60k-after-showing-private-keys-recovers-it/#:~:text=A%20Brazilian%20crypto%20streamer%20lost,but%20it%20was%20too%20late.

In the docs one is asked to export their ethereum private key into a bash variable, this exposes it in bash history and thus reverse search.

If its possible I would change this setup to use docker compose with the .env_file variable, so one can create a .env and run the docker container that way

**Comment by lukemarsden** [comment]
i added a comment to this effect here https://github.com/bacalhau-project/lilypad#run-a-job
